<article class="bugdoc">
    <h2 class="bugdoc-title" id="Bug-Doc:BE7356">BE7356: JUnit assertion in run method will not be noticed by JUnit</h2>
    <h3>JUnit assertion in run method will not be noticed by JUnit</h3>
    <section id="tip">
     <h4 style="border-top: 0pt; padding: 0pt 4pt 4pt 4pt;">Bug info</h4>
                <dl>
                    <dt>BugTypeID</dt>
                    <dd>BE7356</dd>
                    <dt>Tags</dt>
                    <dd>JAVA ,FIND-BUGS</dd>
                    <dt>Category</dt>
                    <dd>Checkers/JAVA</dd>
                    <dt>Authors</dt>
                    <dd>pinpoint</dd>
                </dl>
    <h4>Description</h4>
<p>JUnit assertion in run method will not be noticed by JUnit</p>
<h4>Vulnerability and risk</h4>
<p> A JUnit assertion is performed in a run method. Failed JUnit assertions
just result in exceptions being thrown.
Thus, if this exception occurs in a thread other than the thread that invokes
the test method, the exception will terminate the thread but not result
in the test failing.
</p>
<h4>Likelihood of Exploit</h4>
<p>low</p>

    </section>
</article>
